package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/logger"
	"github.com/gofiber/fiber/v2/middleware/session"
	"github.com/joho/godotenv"

	"csbackend/authenticator"
	db "csbackend/database"
	g "csbackend/global"
	"csbackend/jobs"
	"csbackend/routes"
	"csbackend/util"

	"github.com/gofiber/swagger" // swagger handler
	"github.com/mattn/go-tty"

	_ "csbackend/docs" // docs is generated by Swag CLI, you have to import it.
)

func init() {
	flag.Bool("migrate", false, "migrate database")
	flag.Bool("worker", false, "run worker jobs")
}

// @title           CashierStation Backend Server API
// @version         1.0
// @securityDefinitions.apikey  SessionToken
// @in header
// @name X-Session
func main() {
	flag.Parse()

	err := godotenv.Load(".env")
	if err != nil {
		log.Println("Error loading .env file! Skipping...")
	}

	err = godotenv.Load("/run/secrets/.env")
	if err != nil {
		log.Println("Error loading secrets .env file! Skipping...")
	}

	log.Println("Connecting to database...")

	database, err := db.New()
	if err != nil {
		panic(err)
	}

	doMigration := util.IsFlagPassed("migrate")

	if doMigration {
		log.Println("Migrating database...")
		db.Migrate(database)
		log.Println("Migration done!")
		os.Exit(0)
	}

	sqlDb, err := database.DB()
	if err != nil {
		panic("failed to get database")
	}
	defer sqlDb.Close()

	auth, err := authenticator.New()
	if err != nil {
		panic(err)
	}

	g.Session = session.New()
	g.DB = database
	g.Authenticator = auth

	app := fiber.New(fiber.Config{
		JSONEncoder: json.Marshal,
	})
	port := util.GetPort()

	routes.SetupRoutes(app, database)
	app.Get("/swagger/*", swagger.New(swagger.Config{ // custom
		DeepLinking: false,
		// Expand ("list") or Collapse ("none") tag groups by default
		DocExpansion: "none",
		// Prefill OAuth ClientId on Authorize popup
		OAuth: &swagger.OAuthConfig{
			AppName:  "OAuth Provider",
			ClientId: "21bb4edc-05a7-4afc-86f1-2e151e4ba6e2",
		},
		// Ability to change OAuth2 redirect uri location
		OAuth2RedirectUrl: "http://localhost:8080/swagger/oauth2-redirect.html",
	}))

	app.Use(logger.New())

	doJobs := util.IsFlagPassed("worker")

	if doJobs {
		jobs.StartJob(jobs.StartJobOptions{
			App: app,
		})
	}

	mode := os.Getenv("MODE")
	if mode != "release" {
		go check_termination()
	}

	app.Listen(port)
}

func check_termination() {
	tty, err := tty.Open()
	if err != nil {
		log.Fatal(err)
	}
	defer tty.Close()

	for {
		r, err := tty.ReadRune()
		if err != nil {
			log.Fatal(err)
		}

		if r == 'q' {
			fmt.Println("Terminating...")
			os.Exit(0)
			break
		}
	}
}
