name: CashierStation Backend Deploy
on:
  push:
    tags:
      - 'v*'
jobs:
  deploy:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: dwiandhika/csbackend:${{ steps.vars.outputs.tag }}