definitions:
  user.GET.response:
    properties:
      aud:
        type: string
      email:
        type: string
      email_verified:
        type: boolean
      exp:
        type: integer
      family_name:
        type: string
      given_name:
        type: string
      iat:
        type: integer
      iss:
        type: string
      locale:
        type: string
      name:
        type: string
      nickname:
        type: string
      picture:
        type: string
      sid:
        type: string
      sub:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/callback:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: Callback
      produces:
      - application/json
      responses: {}
      summary: Endpoint the user is redirected to after logging in.
      tags:
      - auth
  /auth/login:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: |-
        dev: http://localhost:8080/auth/login
        prod: https://csbackend.fly.dev/auth/login
      produces:
      - application/json
      responses: {}
      summary: Redirect user to third party login
      tags:
      - auth
  /auth/logout:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: |-
        dev: http://localhost:8080/auth/logout
        prod: https://csbackend.fly.dev/auth/logout
      produces:
      - application/json
      responses: {}
      summary: Log user out
      tags:
      - auth
  /example:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: Example
      produces:
      - application/json
      responses: {}
      tags:
      - example
  /metrics:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: |-
        dev: http://localhost:8080/metrics
        prod: https://csbackend.fly.dev/metrics
      produces:
      - application/json
      responses: {}
      tags:
      - metrics
  /user:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: User
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.GET.response'
      tags:
      - user
swagger: "2.0"
