definitions:
  login.LoginPostResponse:
    properties:
      session_token:
        type: string
      username:
        type: string
    type: object
  register.RegisterPostResponse:
    properties:
      role:
        type: string
      session_token:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  title: CashierStation Backend Server API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: |-
        dev: http://localhost:8080/auth/login
        prod: https://csbackend.fly.dev/auth/login
      parameters:
      - description: Access token from Auth0
        in: query
        name: access_token
        required: true
        type: string
      - description: Username
        in: query
        maxLength: 32
        minLength: 3
        name: username
        required: true
        type: string
      - description: Password (Numeric)
        in: query
        maxLength: 32
        minLength: 6
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/login.LoginPostResponse'
      summary: Login a new employee/owner account
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: |-
        dev: http://localhost:8080/auth/register
        prod: https://csbackend.fly.dev/auth/register
      parameters:
      - description: Access token from Auth0
        in: query
        name: access_token
        required: true
        type: string
      - description: Username
        in: query
        maxLength: 32
        minLength: 3
        name: username
        required: true
        type: string
      - description: Password (Numeric)
        in: query
        maxLength: 32
        minLength: 6
        name: password
        required: true
        type: string
      - description: Role
        enum:
        - owner
        - karyawan
        in: query
        name: role
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/register.RegisterPostResponse'
      summary: Register a new employee/owner account
      tags:
      - auth
  /metrics:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: |-
        dev: http://localhost:8080/metrics
        prod: https://csbackend.fly.dev/metrics
      produces:
      - application/json
      responses: {}
      tags:
      - metrics
  /oauth/callback:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: Callback
      produces:
      - application/json
      responses: {}
      summary: Endpoint the user is redirected to after logging in.
      tags:
      - oauth
  /oauth/login:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: |-
        dev: http://localhost:8080/oauth/login
        prod: https://csbackend.fly.dev/oauth/login
      produces:
      - application/json
      responses: {}
      summary: Redirect user to third party login
      tags:
      - oauth
  /oauth/logout:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: |-
        dev: http://localhost:8080/oauth/logout
        prod: https://csbackend.fly.dev/oauth/logout
      produces:
      - application/json
      responses: {}
      summary: Log user out
      tags:
      - oauth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
