definitions:
  user.GET.response:
    properties:
      profile: {}
    type: object
info:
  contact: {}
paths:
  /auth/callback:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: Callback
      produces:
      - application/json
      responses: {}
      summary: Endpoint the user is redirected to after logging in.
      tags:
      - auth
  /auth/login:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: |-
        dev: http://localhost:8080/auth/login
        prod: https://cs-backend-production.up.railway.app/auth/login
      produces:
      - application/json
      responses: {}
      summary: Redirect user to third party login
      tags:
      - auth
  /auth/logout:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: |-
        dev: http://localhost:8080/auth/logout
        prod: https://cs-backend-production.up.railway.app/auth/logout
      produces:
      - application/json
      responses: {}
      summary: Log user out
      tags:
      - auth
  /example:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: Example
      produces:
      - application/json
      responses: {}
      tags:
      - example
  /user:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: User
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.GET.response'
      tags:
      - user
swagger: "2.0"
