definitions:
  user.GET.response:
    properties:
      aud:
        type: string
      email:
        type: string
      email_verified:
        type: boolean
      exp:
        type: integer
      family_name:
        type: string
      given_name:
        type: string
      iat:
        type: integer
      iss:
        type: string
      locale:
        type: string
      name:
        type: string
      nickname:
        type: string
      picture:
        type: string
      sid:
        type: string
      sub:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact: {}
  title: CashierStation Backend Server API
  version: "1.0"
paths:
  /api/user:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: User
      parameters:
      - description: ID Token
        in: query
        name: id_token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.GET.response'
      security:
      - ApiKeyAuth: []
      tags:
      - user
  /auth/register:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: |-
        dev: http://localhost:8080/auth/register
        prod: https://csbackend.fly.dev/auth/register
      parameters:
      - description: Access token
        in: query
        name: access_token
        required: true
        type: string
      - description: Username
        in: query
        name: username
        required: true
        type: string
      - description: Password
        in: query
        name: password
        required: true
        type: string
      - description: Role
        in: query
        name: role
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Redirect user to third party register
      tags:
      - auth
  /example:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: Example
      produces:
      - application/json
      responses: {}
      tags:
      - example
  /metrics:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: |-
        dev: http://localhost:8080/metrics
        prod: https://csbackend.fly.dev/metrics
      produces:
      - application/json
      responses: {}
      tags:
      - metrics
  /oauth/callback:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: Callback
      produces:
      - application/json
      responses: {}
      summary: Endpoint the user is redirected to after logging in.
      tags:
      - oauth
  /oauth/login:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: |-
        dev: http://localhost:8080/oauth/login
        prod: https://csbackend.fly.dev/oauth/login
      produces:
      - application/json
      responses: {}
      summary: Redirect user to third party login
      tags:
      - oauth
  /oauth/logout:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: |-
        dev: http://localhost:8080/oauth/logout
        prod: https://csbackend.fly.dev/oauth/logout
      produces:
      - application/json
      responses: {}
      summary: Log user out
      tags:
      - oauth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
