name: CashierStation Backend Deploy
on:
  push:
    branches:
      - main
env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_PORT: 22
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      -
        name: Pull image from machine
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          echo "$SSH_PRIVATE_KEY"
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@45.76.144.79 'echo "ssh success"'
