name: CashierStation Backend Deploy
on:
  push:
    tags:
      - 'v*'
env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - name: Build and push Docker image
        run: |
          docker build -t dwiandhika/csbackend .
          docker push dwiandhika/csbackend