name: CashierStation Backend Deploy
on:
  push:
    branches:
      - main
env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_PORT: 22
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      -
        name: Pull image from machine
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /tmp
            ls -a
            echo "env_var:$FIRST_NAME"
            exit 1
          host: ${{ secrets.SSH_HOST }}
          user: root
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          pass: ${{ secrets.SSH_PASS }}
          args: "-tt -vvv"
